default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
      # Another command to release:
      # flutter run --release -t lib/main_production.dart --flavor production
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    # sh "flutter run --release -t lib/main_production.dart --flavor production --no-tree-shake-icons"
    firebase_app_distribution(
      app: ENV["FIREBASE_OPTIONS_ANDROID_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "omar.ameer2333@gmail.com",
      release_notes: "This is the first release using Fastlane. Enjoy! 🚀"
    )
  end
end